name: Release Foundry System

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Criar ZIP
        run: |
          mkdir package
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='package' \
            ./ package/

          cd package
          zip -r ../ikrpg.zip .

      - name: Criar Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ikrpg.zip
            package/system.json